import React, { useEffect, useState } from 'react';
import { getApiError } from '../api/client';
import { assignCategoryAuthor, listCategories } from '../api/services';

export default function EditorCategories() {
  const [categories, setCategories] = useState([]); const [authorIds, setAuthorIds] = useState({}); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(null);
  const load = () => listCategories().then((res) => setCategories(res.data)).catch((err) => setError(getApiError(err))).finally(() => setLoading(false));
  useEffect(load, []);
  const assign = async (categoryId) => { setSaving(categoryId); setError(''); setMessage(''); try { await assignCategoryAuthor(categoryId, authorIds[categoryId]); setMessage('Category assignment updated.'); load(); } catch (err) { setError(getApiError(err)); } finally { setSaving(null); } };
  return <><div className="mb-10 border-b border-line pb-7"><p className="text-xs font-bold uppercase tracking-[0.2em] text-rust">Editor desk</p><h1 className="mt-2 font-display text-5xl font-bold">Categories</h1><p className="mt-4 max-w-xl text-sm leading-6 text-ink/60">The six publishing beats are fixed. Manage which author can write in each one.</p></div>{error && <p className="mb-5 border-l-4 border-rust bg-rust/10 px-4 py-3 text-sm">{error}</p>}{message && <p className="mb-5 border-l-4 border-moss bg-moss/10 px-4 py-3 text-sm">{message}</p>}{loading ? <p className="py-16 text-center text-sm text-ink/60">Loading categories...</p> : <div className="grid gap-4 sm:grid-cols-2">{categories.map((category) => <section key={category.id} className="border border-line bg-white/30 p-5"><p className="font-display text-2xl font-bold">{category.name}</p><p className="mt-2 text-sm text-ink/60">Assigned author: <strong className="text-ink">{category.author?.name || 'Unassigned'}</strong>{category.author?.id && <span className="text-ink/40"> · ID {category.author.id}</span>}</p><div className="mt-5 flex gap-2"><input className="field mt-0" type="number" min="1" placeholder="Author ID" value={authorIds[category.id] || ''} onChange={(e) => setAuthorIds({ ...authorIds, [category.id]: e.target.value })} /><button className="button-primary shrink-0 px-3 py-2" disabled={!authorIds[category.id] || saving === category.id} onClick={() => assign(category.id, authorIds[category.id])}>{saving === category.id ? 'Saving' : 'Assign'}</button></div></section>)}</div>}</>;
}
