import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Login() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const session = await login(form.email, form.password); const destination = location.state?.from?.pathname || (session.role === 'EDITOR' ? '/editor/posts' : '/author/posts'); navigate(destination, { replace: true }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-md py-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-rust">Welcome back</p><h1 className="mt-3 font-display text-5xl font-bold">Sign in</h1><p className="mt-4 text-sm leading-6 text-ink/60">Use your author or editor credentials to continue.</p>{error && <p className="mt-6 border-l-4 border-rust bg-rust/10 px-4 py-3 text-sm">{error}</p>}<form className="mt-8 space-y-5" onSubmit={submit}><div><label className="label" htmlFor="email">Email</label><input className="field" id="email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></div><div><label className="label" htmlFor="password">Password</label><input className="field" id="password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /></div><button className="button-primary w-full" disabled={loading}>{loading ? 'Checking credentials...' : 'Sign in'}</button></form><p className="mt-8 text-sm text-ink/60">Need an author account? <Link className="font-bold text-rust" to="/register">Register here</Link>.</p></div>;
}
